# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='Населённый пункт')),
                ('photo', models.ImageField(blank=True, upload_to='users/', verbose_name='Фото')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('passport', models.CharField(max_length=10, verbose_name='Пасспорт')),
                ('score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sex', models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], default='male', max_length=10, verbose_name='пол')),
                ('social_status', models.CharField(choices=[('schoolboy', 'Школьник'), ('student', 'Студент'), ('working', 'Рабочий'), ('сivil_servant', 'Госслужащий'), ('businessman', 'Предприниматель'), ('unemployed', 'Безработный'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Социальный статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('user',),
            },
        ),
    ]
