# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название предложения')),
                ('slug', models.SlugField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='offers/')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Статус предложения')),
                ('min_score', models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='минимальный скоринговый балл')),
                ('max_score', models.DecimalField(decimal_places=2, default='10', max_digits=10, verbose_name='максимальный скоринговый балл')),
                ('type_offer', models.CharField(choices=[('potreb', 'Потребительский кредит'), ('ipoteka', 'Ипотека'), ('auto', 'Автокредит'), ('kmsb', 'Кредит М и С бизнеса')], default='potreb', max_length=20, verbose_name='Тип предложения')),
                ('begin', models.DateTimeField(verbose_name='Начало ротации')),
                ('end', models.DateTimeField(verbose_name='Окончание ротации')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Название партнёра')),
                ('slug', models.CharField(db_index=True, max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='offers/partner/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, default='2010-01-01', null=True, verbose_name='Дата рождения')),
                ('city', models.CharField(blank=True, default='Москва', max_length=40, verbose_name='Населённый пункт')),
                ('photo', models.ImageField(upload_to='users/', verbose_name='Фото')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('passport', models.CharField(max_length=10, verbose_name='Паспорт')),
                ('score', models.DecimalField(decimal_places=2, default='10', max_digits=10)),
                ('sex', models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], default='male', max_length=10, verbose_name='пол')),
                ('social_status', models.CharField(choices=[('schoolboy', 'Школьник'), ('student', 'Студент'), ('working', 'Рабочий'), ('сivil_servant', 'Госслужащий'), ('businessman', 'Предприниматель'), ('unemployed', 'Безработный'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Социальный статус')),
                ('group', models.CharField(choices=[('superuser', 'Суперпользователь'), ('partner', 'Партнёр'), ('bank', 'Кредитная организация'), ('user', 'Пользователь')], default='user', max_length=20, verbose_name='Группа пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлeн')),
                ('type_status', models.CharField(choices=[('Новый', 'Новый'), ('Отправлено', 'Отправлено')], default='Новый', max_length=20, verbose_name='Статус')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='account.Offer', verbose_name='Предложение')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.Profile', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='account.Partner', verbose_name='Партнёр'),
        ),
        migrations.AlterIndexTogether(
            name='offer',
            index_together=set([('id', 'slug')]),
        ),
    ]
