# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='passport',
            field=models.CharField(max_length=10, verbose_name='Паспорт'),
        ),
    ]
