# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='+7 XXX XXX XXXX', max_length=12, verbose_name='Телефон'),
        ),
    ]
