# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170930_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='Москва', max_length=30, verbose_name='Населённый пункт'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default='01.01.2010', null=True, verbose_name='Дата рождения'),
        ),
    ]
