# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170930_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название предложения')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='offers/')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Статус предложения')),
                ('min_score', models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='минимальный скоринговый балл')),
                ('max_score', models.DecimalField(decimal_places=2, default='10', max_digits=10, verbose_name='максимальный скоринговый балл')),
                ('type_offer', models.CharField(choices=[('potreb', 'Потребительский кредит'), ('ipoteka', 'Ипотека'), ('auto', 'Автокредит'), ('kmsb', 'Кредит М и С бизнеса')], default='potreb', max_length=20, verbose_name='Тип предложения')),
                ('begin', models.DateTimeField(verbose_name='Начало ротации')),
                ('end', models.DateTimeField(verbose_name='Окончание ротации')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название партнёра')),
                ('slug', models.CharField(db_index=True, max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='offers/partner/<django.db.models.fields.CharField>', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('type_status', models.CharField(choices=[('new', 'Новый'), ('sent', 'Отправлено')], default='new', max_length=20, verbose_name='Статус')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='account.Offer', verbose_name='Предложение')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.Profile', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='account.Partner', verbose_name='Партнёр'),
        ),
        migrations.AlterIndexTogether(
            name='offer',
            index_together=set([('id', 'slug')]),
        ),
    ]
