# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20171009_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, upload_to='offers/partner/', verbose_name='Изображение'),
        ),
    ]
