# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20171009_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type_status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Отправлено', 'Отправлено')], default='Новый', max_length=20, verbose_name='Статус'),
        ),
    ]
