# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20171009_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.CharField(choices=[('superuser', 'Суперпользователь'), ('partner', 'Партнёр'), ('bank', 'Кредитная организация'), ('user', 'Пользователь')], default='user', max_length=20, verbose_name='Группа пользователя'),
        ),
    ]
