# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20171009_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='users/', verbose_name='Фото'),
        ),
    ]
