"""
Django settings for unicom24project project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v64!-b-zo^pc3$)&lkx-ws3arrn@*)6p*32*z4q&z2782(by1#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['myunicom24.herokuapp.com', 'localhost', '127.0.0.1']

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dd738nl06ba0mj',
        'USER': 'zxjukrucquxfyo',
        'PASSWORD': '99c018fc8c94d25be7d4a16975d6a84e5f50eb92729cd4c35e8f480e8b6a5039',
        'HOST': 'ec2-174-129-239-0.compute-1.amazonaws.com',
        'PORT': '5432',
    }
}

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'yuta1986gr@gmail.com'
EMAIL_HOST_PASSWORD = '123'
DEFAULT_FROM_EMAIL = ''
DEFAULT_TO_EMAIL = 'yuta1986gr@gmail.com'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'account.authentication.EmailAuthBackend',
)
#logger.debug()
#logger.info()
#logger.warning()
#logger.error()
#logger.critical()

LOGGING = {
              'version': 1,
              'disable_existing_loggers': False,
              'loggers':
                  {
                      'name1': {
                          'handlers': ['console', 'file'],
                          'level': 'DEBUG',
                      },
                      'name2': {
                          'handlers': ['console', 'file2'],
                          'level': 'DEBUG',
                      }
                  },
              'handlers':
              {
                      'console': {
                          'level': 'INFO',
                          'class': 'logging.StreamHandler',
                      },
                      'file': {
                          'level': 'ERROR',
                          'class': 'logging.FileHandler',
                          'filename': os.path.join(BASE_DIR, 'debug.log'),
                          'formatter': 'verbose',
                      },
                      'file2': {
                          'level': 'ERROR',
                          'class': 'logging.FileHandler',
                          'filename': os.path.join(BASE_DIR, 'debug_unicom24.log'),
                          'formatter': 'simple',
                      },
              },
              'formatters': {
              },
          },


# REST_FRAMEWORK = {
#     # Use Django's standard `django.contrib.auth` permissions,
#     # or allow read-only access for unauthenticated users.
#     'DEFAULT_PERMISSION_CLASSES': [
#         # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
#         'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser',),
#     ],
#     'PAGE_SIZE': 10
# }

REST_FRAMEWORK = {
'DEFAULT_PERMISSION_CLASSES': [
    'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
]
}
